### ISSUE TITLE
Flutter使用CupertinoAlertDialog 报 'alertDialogLabel' was called on null.

### ISSUE THREAD

**Issue by shichunlei** [shichunlei/flutter_app#3]
报错信息

I/flutter (23496): Another exception was thrown: NoSuchMethodError: The getter 'alertDialogLabel' was called on null.
I/flutter (23496): ###LogUtil###  e  Error caught by widgets library, thrown building LayoutBuilder.
I/flutter (23496): NoSuchMethodError: The getter 'alertDialogLabel' was called on null.
I/flutter (23496): Receiver: null
I/flutter (23496): Tried calling: alertDialogLabel
I/flutter (23496): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (23496): #1      CupertinoAlertDialog.build.<anonymous closure> (package:flutter/src/cupertino/dialog.dart:245:40)
I/flutter (23496): #2      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
I/flutter (23496): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter (23496): #4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
I/flutter (23496): #5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
I/flutter (23496): #6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter (23496): #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
I/flutter (23496): #8      _RenderLayoutBuilder.performLayout (

**Comment by shichunlei** [comment]
[解决](https://juejin.im/post/5c417d626fb9a049ec6b5d44)
